### ISSUE TITLE
API végpont tesztelés teljesítmény szempontból

### ISSUE THREAD

**Issue by zolykovacs** [BME-MIT-IET/iet-hf-2024-lg_iet_lab#10]
Az API utóbb felsorolt végpontjainak tesztelése/vizsgálata performancia szempontból. Az egyes végpontokon elvégzett performance vizsgálatok összehasonlítása és ezek dokumentálása.

Vizsgálandó API végpontok:

GET:
-api/resource/all
-api/resource/:resourceId
-/api/dataset/withresource/{resourceId}

POST:
-api/resource

PUT:
-/api/resource/{resourceId}

Összetett, több lépésből álló teszt végrehajtása.

Valós felhasználást szimuláló teszt végrehajtása.

A tesztek után:

Konzekvenciák levonása és a backendre vonatkozó fejlesztési ötletek megfogalmazása.

**Comment by matesze41nons** [comment]
Én végzem majd a dokumentáció írását illetve segédkezem a tesztesetek tervezésében.

**Comment by zolykovacs** [comment]
Az én feladataim:
 -tesztesetek tervezése @matesze41nons  segítségével
 -az egyes tesztek kiinduló állapotának felsetupolása
 -a teszteredmények eljuttatása @matesze41nons a dokumentációhoz

**Comment by zolykovacs** [comment]
A valós-szenzor-szimulációnál fontos részlet, hogy ott a teszt 2 percig, futott, azon megfontolásból, hogy valamennyire közelebb kerüljünk a valósághoz. @matesze41nons

**Comment by matesze41nons** [comment]
@zolykovacs Ma kérlek töltsd ki az általam üresen hagyott helyeket a dokumentációban. Este átolvassuk a végterméket és majd kitesszük reviewra.

**Comment by matesze41nons** [comment]
> A valós-szenzor-szimulációnál fontos részlet, hogy ott a teszt 2 percig, futott, azon megfontolásból, hogy valamennyire közelebb kerüljünk a valósághoz. @matesze41nons

Ezt befoglaltam a dokumentációba.

**Comment by zolykovacs** [comment]
> @zolykovacs Ma kérlek töltsd ki az általam üresen hagyott helyeket a dokumentációban. Este átolvassuk a végterméket és majd kitesszük reviewra.

@matesze41nons 
Megcsináltam a kért dolgot, ezen kívül hozzáadtam a hasznát forrásokat a dokumentációhoz. Véleményem szerint a feladat ránk eső része elkészült. 05.16 (csütörtökön) mindenképp tartsunk egy megbeszélést, véglegesítsük a dolgokat és hozzuk létre a pull-requestet.

**Comment by zolykovacs** [comment]
A Performance-Testing branchet hozzárendeltem az issuehoz, ezt valószínűleg rögtön az elején kellett volna, de jó hogy utólag észre lett véve. @matesze41nons
