### ISSUE TITLE
API végpontok integrációs és regressziós tesztelése, API dokumentáció írása Postman segítségével

### ISSUE THREAD

**Issue by kolcsong** [BME-MIT-IET/iet-hf-2024-lg_iet_lab#11]
A feladatom az API végpontok tesztelése olyan szempontból, hogy az egyes végpontokhoz intézett kérésekre érkező válaszok státuszkódja megfelelő-e, illetve a válaszok tartalma megfelelő formátumban van-e, illetve, hogy megfelelő adatok kerültek-e lekérdezésre.

A feladatom végrehajtásának ellenőrzését a csapat többi tagja hajtja végre.

**Comment by kolcsong** [comment]
A dokumentáció készen áll az átnézésre, és elfogadásra.

**Comment by csaba012** [comment]
Mergel-tél a main-ba is. Lezárom az Issue-t
