### ISSUE TITLE
Manuális kód átvizsgálás elvégzése az alkalmazás egy részére, statikus analízis eszköz futtatása és jelzett hibák átnézése

### ISSUE THREAD

**Issue by csaba012** [BME-MIT-IET/iet-hf-2024-lg_iet_lab#12]
Előzetes megbeszélések alapján rám jutott ennek a feladatnak az elvégzése. 
A feladatom során a projekttel való ismerkedés során folyamatosan vizsgálom is a kódot, hátha találok code smell-eket, illetve ebben a segítségemre lesz a SonarLint plugin is. 
A manuális átvizsgálás után pedig összekötöm a repository-t a SonarClouddal és így mélyebb analizálást végzek.
A SonarCloud által észrevett hibákat átvizsgálom, megvitatom társaimmal, hogy melyek a tényleges hibák, vagy mely javaslatokat fogadjuk el. A megbeszéltek alapján pedig javítom a kódot.

**Comment by kolcsong** [comment]
A Pull-request mergelésre került, ezért lezárom ezt az issue-t.
