### ISSUE TITLE
GET válasz a /api/dataset/{datasetId} URL-re küldött kérésre rossz resourceId-t ad vissza

### ISSUE THREAD

**Issue by kolcsong** [BME-MIT-IET/iet-hf-2024-lg_iet_lab#3]
![image](https://github.com/BME-MIT-IET/iet-hf-2024-lg_iet_lab/assets/166651149/5192d40c-e470-4da1-9fae-9273c16e2401)
Ezen a képen az látszik, hogy a resourceId mező értéke 51, azonban 3-nak kellene lennie az adatbázis szerint.
![image](https://github.com/BME-MIT-IET/iet-hf-2024-lg_iet_lab/assets/166651149/c3dea81d-932b-4be8-80fa-887bee712331)

**Comment by zolykovacs** [comment]
A probléma megoldódott.
